import { statusLabel } from './portal-utils.js';

const ADMIN_EMAIL='contact@neptunebusiness.com';
function sender(env){return env.AUTH_FROM_EMAIL||'Neptune Media <onboarding@resend.dev>';}
async function send(env,payload){
  if(!env.RESEND_API_KEY){console.error('resend_not_configured');return {ok:false,error:'email_service_not_configured'};}
  const response=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${env.RESEND_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify(payload)});
  const raw=await response.text(),result=parseJson(raw);
  if(!response.ok){console.error('resend_failed',{status:response.status,code:result.name||result.code||'',message:result.message||raw.slice(0,300),from:payload.from,to:payload.to});return {ok:false,error:'email_send_failed'};}
  if(!result.id){console.error('resend_id_missing',{status:response.status,response:result,to:payload.to});return {ok:false,error:'email_send_unconfirmed'};}
  console.log('resend_email_sent',{emailId:result.id,to:payload.to,subject:payload.subject});return {ok:true,id:result.id};
}
export function portalUrl(requestUrl,email,step=''){const url=new URL('/espace-client/',new URL(requestUrl).origin);url.searchParams.set('email',email);if(step)url.searchParams.set('step',step);return url.toString();}
export async function sendCode(env,requestUrl,email,code){const url=portalUrl(requestUrl,email,'code');return send(env,{from:sender(env),to:[email],subject:`${code} · Votre code Neptune Media`,html:layout('Votre code sécurisé',`<p style="font-size:34px;letter-spacing:.22em;font-weight:800">${code}</p><p>Ce code expire dans 10 minutes et ne peut être utilisé qu’une fois.</p>${button(url,'Saisir mon code')}`),text:`Votre code Neptune Media : ${code}. Il expire dans 10 minutes. ${url}`});}
export async function sendAccess(env,requestUrl,email,name=''){const url=portalUrl(requestUrl,email);return send(env,{from:sender(env),to:[email],subject:'Accédez à votre espace Neptune Media',html:layout('Votre espace client est prêt',`<p>${name?`Bonjour ${escapeHtml(name)}, `:''}retrouvez vos réservations, votre préparation, votre suivi, vos rushs et vos livrables dans un seul espace permanent.</p>${button(url,'Accéder à mon espace')}<p>Votre connexion se fait avec un code reçu par e-mail, sans mot de passe.</p>`),text:`Votre espace Neptune Media est prêt : ${url}`});}
export async function sendOrderConfirmation(env,requestUrl,email,payload={}){const url=portalUrl(requestUrl,email),title=String(payload.title||payload.productName||payload.format||'Votre passage Neptune Media');return send(env,{from:sender(env),to:[email,ADMIN_EMAIL].filter((value,index,array)=>value&&array.indexOf(value)===index),subject:'Votre réservation Neptune Media est confirmée',html:layout('Votre réservation est confirmée',`<p><strong>${escapeHtml(title)}</strong> a été ajouté à votre compte permanent.</p><p>Vous pouvez maintenant choisir ou consulter votre rendez-vous, préparer l’interview et suivre votre passage jusqu’à la livraison.</p>${button(url,'Accéder à mon espace')}`),text:`Votre réservation ${title} est confirmée. Accédez à votre espace : ${url}`});}
export async function sendAppointmentConfirmation(env,requestUrl,email,payload={}){const url=portalUrl(requestUrl,email),appointment=formatAppointment(payload.appointmentAt),title=String(payload.title||payload.format||'Votre passage Neptune Media');return send(env,{from:sender(env),to:[email,ADMIN_EMAIL].filter((value,index,array)=>value&&array.indexOf(value)===index),subject:'Votre rendez-vous Neptune Media est confirmé',html:layout('Votre rendez-vous est confirmé',`<p><strong>${escapeHtml(title)}</strong></p><p style="font-size:20px;font-weight:700">${escapeHtml(appointment)}</p><p>Votre espace client est à jour.</p>${button(url,'Préparer mon passage')}`),text:`Votre rendez-vous Neptune Media est confirmé : ${appointment}. ${url}`});}
export async function sendStatusUpdate(env,requestUrl,email,payload={}){
  const url=portalUrl(requestUrl,email),label=statusLabel(payload.status),title=String(payload.title||'Votre passage Neptune Media'),next=String(payload.nextAction||'Consultez votre espace client pour la suite.');
  const recipients=[email,ADMIN_EMAIL].filter((value,index,array)=>value&&array.indexOf(value)===index);
  return send(env,{from:sender(env),to:recipients,subject:`Neptune Media · ${label}`,html:layout(label,`<p><strong>${escapeHtml(title)}</strong></p><p>Le suivi vient d’être mis à jour.</p><div style="padding:18px;border-radius:16px;background:#f3f1ff"><small style="color:#6658a8">PROCHAINE ACTION</small><p style="margin:6px 0 0;font-weight:700">${escapeHtml(next)}</p></div>${button(url,'Voir le suivi complet')}`),text:`${title} — ${label}. Prochaine action : ${next}. ${url}`});
}
export async function sendDeletionRequest(env,requestUrl,email,payload={}){
  const url=portalUrl(requestUrl,email),recipients=[email,ADMIN_EMAIL].filter((value,index,array)=>value&&array.indexOf(value)===index);
  return send(env,{from:sender(env),to:recipients,subject:'Demande de suppression de compte Neptune Media',html:layout('Demande de suppression enregistrée',`<p>La demande concernant <strong>${escapeHtml(email)}</strong> a été enregistrée.</p><p>Neptune Media vérifiera les obligations légales de conservation avant suppression ou anonymisation.</p>${button(url,'Consulter mon espace')}`),text:`Demande de suppression enregistrée pour ${email}. ${url}`});
}
function layout(title,content){return `<div style="font-family:Arial,sans-serif;max-width:620px;margin:auto;padding:34px;color:#121326"><p style="letter-spacing:.16em;color:#6d55e8;font-weight:700">NEPTUNE MEDIA</p><h1>${escapeHtml(title)}</h1>${content}</div>`;}
function button(url,label){return `<p><a href="${url}" style="display:inline-block;padding:14px 22px;border-radius:999px;background:linear-gradient(120deg,#4267ff,#8d4cff,#ef4ba2);color:#fff;text-decoration:none;font-weight:700">${escapeHtml(label)}</a></p>`;}
function formatAppointment(value){const date=new Date(value||'');if(Number.isNaN(date.getTime()))return 'Le créneau confirmé est disponible dans votre espace client.';return new Intl.DateTimeFormat('fr-FR',{dateStyle:'full',timeStyle:'short',timeZone:'Europe/Paris'}).format(date);}
function escapeHtml(value){return String(value||'').replace(/[&<>"']/gu,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function parseJson(value){try{return JSON.parse(String(value||'{}'));}catch{return {};}}