import { bookingLink, bookingUrl, absolute, episodeCard, escapeHtml, isoDuration, layout, paragraphs, toList } from './public-layout.js';

export function renderDirect(origin, catalog) {
  const live = publishedEpisodes(catalog).filter((item) => item.metadata?.live !== false && (item.metadata?.fullEpisode || item.videoUrl?.startsWith('/media/')));
  const description = 'Regardez Neptune Media en continu, 24 heures sur 24, avec une programmation pilotée depuis le Studio Admin.';
  return layout({ origin, title: 'Neptune Media en direct — Web TV 24h/24', description, canonical: `${origin}/direct/`, structuredData: [{ '@context': 'https://schema.org', '@type': 'BroadcastService', name: 'Neptune Media — Direct', description, url: `${origin}/direct/` }], body: `<main class="seo-main live-page"><nav class="breadcrumbs"><a href="/">Accueil</a><span>›</span><span>En direct</span></nav><section class="seo-hero live-page-hero"><span class="live-badge"><i></i> EN DIRECT · 24H/24</span><h1>La chaîne Neptune Media ne s’arrête jamais.</h1><p>Les émissions s’enchaînent automatiquement selon l’ordre défini dans le Studio. Reprenez le direct à tout moment ou choisissez une émission du programme.</p></section><section class="live-channel" data-live-channel><div class="live-stage"><video data-live-video autoplay muted controls playsinline preload="metadata"></video><div class="live-overlay"><div><span data-live-program>NEPTUNE MEDIA</span><strong data-live-title>Chargement de l’antenne…</strong></div><button type="button" data-live-sound>Activer le son</button></div></div><aside class="live-guide"><div class="live-guide-head"><div><span class="eyebrow">Programme continu</span><h2>À l’antenne</h2></div><button type="button" class="btn btn-secondary" data-live-resync>Reprendre le direct</button></div><div data-live-playlist>${live.length ? '' : '<p class="empty-state">Les premières émissions sont en cours de mise à l’antenne.</p>'}</div></aside></section><section class="related"><span class="eyebrow">À la demande</span><h2>Choisir une émission</h2><div class="seo-grid">${cards(origin, catalog, live)}</div></section></main><script type="module" src="/live-channel.js?v=1"></script>` });
}

export function renderEmissions(origin, catalog) {
  const episodes = publishedEpisodes(catalog);
  const publishedProgramIds = new Set(episodes.map((item) => item.programId));
  const programs = catalog.programs.filter((item) => publishedProgramIds.has(item.id));
  const pills = `<nav class="program-pills" aria-label="Programmes"><a href="/emissions/">Tout voir</a>${programs.map((item) => `<a href="/programmes/${encodeURIComponent(item.slug)}/">${escapeHtml(item.name)}</a>`).join('')}</nav>`;
  return layout({ origin, title: 'Toutes les émissions — Neptune Media', description: 'Découvrez les émissions, extraits et trajectoires entrepreneuriales produites par Neptune Media.', canonical: `${origin}/emissions/`, body: `<main class="seo-main"><section class="seo-hero"><span class="eyebrow">La chaîne Neptune Media</span><h1>Des histoires d’entreprise qui méritent l’antenne.</h1><p>Explorez les émissions par programme, découvrez les trajectoires et regardez les moments qui donnent du relief à une expertise.</p><p><a class="btn btn-primary" href="/direct/">Regarder la chaîne en direct</a></p></section>${pills}<section class="seo-grid">${cards(origin, catalog, episodes)}</section></main>` });
}

export function renderProgram(origin, catalog, program) {
  const episodes = publishedEpisodes(catalog).filter((item) => item.programId === program.id);
  return layout({ origin, title: `${program.name} — Programme Neptune Media`, description: program.description || `Retrouvez les émissions du programme ${program.name}.`, canonical: `${origin}/programmes/${encodeURIComponent(program.slug)}/`, structuredData: [{ '@context': 'https://schema.org', '@type': 'CollectionPage', name: program.name, description: program.description, url: `${origin}/programmes/${program.slug}/` }], body: `<main class="seo-main"><nav class="breadcrumbs"><a href="/">Accueil</a><span>›</span><a href="/emissions/">Émissions</a><span>›</span><span>${escapeHtml(program.name)}</span></nav><section class="seo-hero"><span class="eyebrow">Programme</span><h1>${escapeHtml(program.name)}</h1><p>${escapeHtml(program.description)}</p></section><section class="seo-grid">${cards(origin, catalog, episodes)}</section></main>` });
}

export function renderEpisode(origin, catalog, episode) {
  const program = catalog.programs.find((item) => item.id === episode.programId);
  const metadata = episode.metadata || {};
  const description = metadata.metaDescription || episode.description || 'Une émission Neptune Media.';
  const canonical = `${origin}/emissions/${encodeURIComponent(episode.slug)}/`;
  const transcript = String(metadata.transcript || '').trim();
  const questions = toList(metadata.questions);
  const guest = metadata.guestName || '';
  const company = metadata.guestCompany || '';
  const related = publishedEpisodes(catalog).filter((item) => item.id !== episode.id && item.programId === episode.programId).slice(0, 3);
  const videoData = { '@context': 'https://schema.org', '@type': 'VideoObject', name: episode.title, description, contentUrl: absolute(origin, episode.videoUrl), embedUrl: canonical, url: canonical };
  const thumbnailUrl = absolute(origin, episode.posterUrl);
  const uploadDate = validIsoDate(episode.publishedAt);
  const duration = isoDuration(episode.durationSeconds);
  if (thumbnailUrl) videoData.thumbnailUrl = thumbnailUrl;
  if (uploadDate) videoData.uploadDate = uploadDate;
  if (duration) videoData.duration = duration;
  if (guest) videoData.actor = { '@type': 'Person', name: guest };
  return layout({ origin, title: metadata.seoTitle || `${episode.title} — Neptune Media`, description, canonical, image: absolute(origin, episode.posterUrl), structuredData: [videoData, breadcrumbs(origin, program, episode)], body: `<main class="seo-main episode-page"><nav class="breadcrumbs"><a href="/">Accueil</a><span>›</span><a href="/emissions/">Émissions</a><span>›</span><span>${escapeHtml(episode.title)}</span></nav><article><div class="episode-player"><video controls playsinline preload="metadata" poster="${escapeHtml(absolute(origin, episode.posterUrl))}"><source src="${escapeHtml(absolute(origin, episode.videoUrl))}" type="video/mp4"></video></div><div class="episode-layout"><div class="episode-copy"><span class="eyebrow">${escapeHtml(program?.name || 'Neptune Media')}</span><h1>${escapeHtml(episode.title)}</h1>${guest ? `<p class="guest-line">Avec <strong>${escapeHtml(guest)}</strong>${company ? ` · ${escapeHtml(company)}` : ''}</p>` : ''}<p class="lead">${escapeHtml(episode.description)}</p><div class="episode-actions"><button class="btn btn-dark" type="button" data-native-share>Partager l’émission</button><a class="btn btn-primary" href="${bookingLink(episode)}">Voir les créneaux disponibles</a></div>${questions.length ? `<section class="answer-block"><h2>Les questions abordées</h2><ul>${questions.map((item) => `<li>${escapeHtml(item)}</li>`).join('')}</ul></section>` : ''}${transcript ? `<section class="transcript"><h2>Transcription</h2>${paragraphs(transcript)}</section>` : `<section class="answer-block"><h2>Ce que cette émission montre</h2><p>Une parole entrepreneuriale claire, une scène vécue et un dispositif éditorial conçu pour être regardé, compris et partagé.</p></section>`}</div><aside><div class="offer-card"><span class="eyebrow">Passer à l’écran</span><h2>Votre histoire peut devenir une émission.</h2><p>Choisissez le format qui révèle votre trajectoire ou construit un concept autour de votre marque.</p><a class="btn btn-primary btn-block" href="${bookingLink(episode)}">Choisir mon format</a></div></aside></div></article>${related.length ? `<section class="related"><span class="eyebrow">À voir ensuite</span><h2>Dans le même programme</h2><div class="seo-grid">${cards(origin, catalog, related)}</div></section>` : ''}</main><script src="/episode-page.js?v=3"></script>` });
}

export function renderInformation(origin, title, description, type) {
  const contents = { legal: `<h2>Éditeur</h2><p>Neptune Business & Média. Les informations juridiques complètes de la société sont disponibles sur les supports officiels de Neptune Business.</p><h2>Hébergement</h2><p>Le service est hébergé sur l’infrastructure Cloudflare.</p><h2>Propriété intellectuelle</h2><p>Les vidéos, marques, textes et éléments graphiques restent protégés par les droits applicables.</p>`, privacy: `<h2>Données mesurées</h2><p>La Web TV mesure les lectures, le temps de visionnage, la progression, les partages et les clics vers la réservation afin d’améliorer les programmes et d’attribuer les conversions.</p><h2>Identifiant de session</h2><p>Un identifiant aléatoire est conservé localement. Il ne contient ni nom ni adresse e-mail.</p><h2>Vos droits</h2><p>Écrivez à <a href="mailto:contact@neptunebusiness.com">contact@neptunebusiness.com</a>.</p>`, contact: `<h2>Parler de votre projet</h2><p>Écrivez à <a href="mailto:contact@neptunebusiness.com">contact@neptunebusiness.com</a>.</p><p><a class="btn btn-primary" href="${bookingUrl('contact_page')}">Voir les créneaux et les offres</a></p>` };
  const slug = type === 'legal' ? 'mentions-legales' : type === 'privacy' ? 'confidentialite' : 'contact';
  return layout({ origin, title: `${title} — Neptune Media`, description, canonical: `${origin}/${slug}/`, body: `<main class="seo-main info-page"><nav class="breadcrumbs"><a href="/">Accueil</a><span>›</span><span>${escapeHtml(title)}</span></nav><article><span class="eyebrow">Neptune Media</span><h1>${escapeHtml(title)}</h1>${contents[type]}</article></main>` });
}

export function renderNotFound(origin) { const body = layout({ origin, title: 'Page introuvable — Neptune Media', description: 'Cette page n’existe pas.', canonical: `${origin}/404`, body: '<main class="seo-main info-page"><article><h1>Cette émission n’est plus à l’antenne.</h1><p><a class="btn btn-primary" href="/emissions/">Voir toutes les émissions</a></p></article></main>' }); return new Response(body, { status: 404, headers: { 'Content-Type': 'text/html; charset=utf-8' } }); }
function publishedEpisodes(catalog) { return (catalog.episodes || []).filter((item) => item.status === 'published' && item.slug && item.videoUrl && item.posterUrl); }
function cards(origin, catalog, list) { return list.map((item) => episodeCard(origin, catalog, item)).join('') || '<div class="empty-state"><h2>Les prochaines émissions arrivent.</h2><p>Le Studio Neptune prépare la programmation.</p></div>'; }
function breadcrumbs(origin, program, episode) { return { '@context': 'https://schema.org', '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Accueil', item: `${origin}/` }, { '@type': 'ListItem', position: 2, name: program?.name || 'Émissions', item: program ? `${origin}/programmes/${program.slug}/` : `${origin}/emissions/` }, { '@type': 'ListItem', position: 3, name: episode.title, item: `${origin}/emissions/${episode.slug}/` }] }; }
function validIsoDate(value) { const timestamp = Date.parse(String(value || '')); return Number.isFinite(timestamp) ? new Date(timestamp).toISOString() : ''; }
